# action.yml
name: 'iSamples Vocabulary Action'
description: 'Runs various scripts associated with the iSamples vocabulary repository'
inputs:
  action:  # id of input
    description: 'Which action to run -- defaults to uijson'
    required: true
    default: 'uijson'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.action }}