# Integration test harness useful for testing the GitHub Action itself

# This can be run locally using act (https://github.com/nektos/act) like this:
# act -v -j build --
# This will build the docker image that packages the GitHub Action and run it, with verbose logging to show each step in detail
name: build
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Verify that the Docker image for the action builds
        run: docker build . --file Dockerfile
      - name: uijson integration test
        uses: ./
        with:
          action: uijson
          path: ${{ github.workspace }}/src/CVJSON
          inputttl: material_sample_type|material_type|sampled_feature_type
          inputvocaburi: spec:specimentypevocabulary|mat:materialsvocabulary|sf:sampledfeaturevocabulary
