# Integration test harness useful for testing the GitHub Action itself
name: Integration Test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Vocabulary action
        uses: isamplesorg/vocabularies@main